In [1]:
import torch

1. Tensor Basic

        1.1 Creating Tensors

In [2]:
#1.1.1 creating empty tensor
x= torch.empty(2) #1d
print(x)
y= torch.empty(2,2) #2d
print(y)
z= torch.empty(2,2,2) #3d
print(z)

tensor([0., 0.])
tensor([[0.0000e+00, 0.0000e+00],
        [3.0032e-33, 4.5907e-41]])
tensor([[[0.0000e+00, 0.0000e+00],
         [4.2313e+21, 1.0513e-05]],

        [[6.4535e-10, 1.7567e-04],
         [6.8255e-07, 2.0659e+20]]])


In [3]:
#1.1.2 creating random tensor
x= torch.rand(2) #1d
print(x)
y= torch.rand(2,2) #2d
print(y)
z= torch.rand(2,2,2) #3d
print(z)

tensor([0.6894, 0.9574])
tensor([[0.1371, 0.0507],
        [0.3135, 0.6874]])
tensor([[[0.8542, 0.0866],
         [0.7995, 0.1249]],

        [[0.0420, 0.4299],
         [0.9630, 0.4287]]])


In [4]:
#1.1.3 creating zeros tensor
x= torch.zeros(2) #1d
print(x)
y= torch.zeros(2,2) #2d
print(y)
z= torch.zeros(2,2,2) #3d
print(z)

tensor([0., 0.])
tensor([[0., 0.],
        [0., 0.]])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


In [5]:
#1.1.4 creating ones tensor
#can create as many dimensions as wanted
x= torch.ones(2,2,2) #3d
print(x)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])


In [6]:
#1.1.5 creating manual tensor
z= torch.tensor([2.22, 3.1])
print(z)

tensor([2.2200, 3.1000])


        1.2 Adding Data types for tensor elements

In [7]:
#1.2.1 normally its float32
x= torch.rand(2,2)
print(x.dtype)

torch.float32


In [8]:
#1.2.2 changing dtype
x= torch.ones(2,2, dtype=torch.int)
print(x.dtype)
y= torch.ones(2,2, dtype=torch.double)
print(y.dtype)
z= torch.ones(2,2, dtype=torch.long)
print(z.dtype)
x1 = torch.ones(2,2, dtype=torch.float16)
print(x1.dtype)

torch.int32
torch.float64
torch.int64
torch.float16


        1.3 Size of tensor

In [9]:
print(x1.size())

torch.Size([2, 2])


        1.4 Basic arithmetic operation with tensors

In [10]:
# value init
x= torch.rand(2,2)
print(x)
y= torch.rand(2,2)
print(y)


tensor([[0.8379, 0.3549],
        [0.7811, 0.9980]])
tensor([[0.4256, 0.7775],
        [0.7358, 0.6980]])


In [11]:
#1.4.1 addition
z= torch.add(x,y)   # OR z= x+y
y.add_(x) #adds value of x and y and stores in y
print(z)
print(y)

tensor([[1.2635, 1.1324],
        [1.5169, 1.6960]])
tensor([[1.2635, 1.1324],
        [1.5169, 1.6960]])


In [12]:
#1.4.2 substraction
z= torch.sub(x,y) #OR z= x-y
y.sub_(x)  #OR y= y-x
print(z)
print(y)

tensor([[-0.4256, -0.7775],
        [-0.7358, -0.6980]])
tensor([[0.4256, 0.7775],
        [0.7358, 0.6980]])


In [13]:
#1.4.3 multiplication
z= torch.mul(x,y) #OR z=x*y
y.mul_(x)
print(z)
print(y)

tensor([[0.3566, 0.2760],
        [0.5747, 0.6966]])
tensor([[0.3566, 0.2760],
        [0.5747, 0.6966]])


In [14]:
#1.4.4 division
z= torch.div(x,y) #OR z=x/y
y.div_(x) #OR y= y/x
print(z)
print(y)

tensor([[2.3498, 1.2862],
        [1.3590, 1.4326]])
tensor([[0.4256, 0.7775],
        [0.7358, 0.6980]])


        1.5 Slicing

In [15]:
#syntax: tensor[selected rows, selected column] {use ':' to select all}
x= torch.rand(3,4)
print(x)
print(x[:,0])
print(x[1,:])
print(x[1,2])
print(x[:2])
print(x[1,1].item()) #'.item' outputs actual value of the element of tensor. "Only one element can be picked"

tensor([[0.7330, 0.3537, 0.8305, 0.4612],
        [0.4602, 0.0617, 0.9977, 0.3546],
        [0.7993, 0.7024, 0.6389, 0.0982]])
tensor([0.7330, 0.4602, 0.7993])
tensor([0.4602, 0.0617, 0.9977, 0.3546])
tensor(0.9977)
tensor([[0.7330, 0.3537, 0.8305, 0.4612],
        [0.4602, 0.0617, 0.9977, 0.3546]])
0.06167846918106079


        1.6 Resizing/ Reshaping tensor

In [16]:
x= torch.rand(4,4)
print(x)
y= x.view(16)
print(y)
print(y.size())
y= x.view(2,8)
print(y)
print(y.size())
y= x.view(8,2)
print(y)
print(y.size())

tensor([[0.1559, 0.3288, 0.5715, 0.1673],
        [0.5964, 0.7977, 0.1694, 0.3175],
        [0.0583, 0.2366, 0.2936, 0.6485],
        [0.7612, 0.4768, 0.2010, 0.7019]])
tensor([0.1559, 0.3288, 0.5715, 0.1673, 0.5964, 0.7977, 0.1694, 0.3175, 0.0583,
        0.2366, 0.2936, 0.6485, 0.7612, 0.4768, 0.2010, 0.7019])
torch.Size([16])
tensor([[0.1559, 0.3288, 0.5715, 0.1673, 0.5964, 0.7977, 0.1694, 0.3175],
        [0.0583, 0.2366, 0.2936, 0.6485, 0.7612, 0.4768, 0.2010, 0.7019]])
torch.Size([2, 8])
tensor([[0.1559, 0.3288],
        [0.5715, 0.1673],
        [0.5964, 0.7977],
        [0.1694, 0.3175],
        [0.0583, 0.2366],
        [0.2936, 0.6485],
        [0.7612, 0.4768],
        [0.2010, 0.7019]])
torch.Size([8, 2])


        1.7 Tensor <-> numpy array

In [17]:
import numpy as np

In [18]:
#1.7.1 tensor -> numpy array
x= torch.rand(2,2)
print(x)
y= x.numpy()
print(y,type(y))
#If tensor is in cpu but not in gpu then both objects 
#(the tensor and numpy array) share the same memory location.
#both x and y will change if only x or only y is changed
x.add_(1)
print(x,y)

tensor([[0.2388, 0.3971],
        [0.7667, 0.0013]])
[[0.23875272 0.39710343]
 [0.76674193 0.00134712]] <class 'numpy.ndarray'>
tensor([[1.2388, 1.3971],
        [1.7667, 1.0013]]) [[1.2387527 1.3971034]
 [1.766742  1.0013471]]


In [19]:
#1.7.2 numpy array -> tensor
x= np.array([[1,2,3],[4,5,6]], dtype= 'int16')
print(x)
y= torch.from_numpy(x)
print(y)
#If tensor is in cpu but not in gpu then both objects 
#(the tensor and numpy array) share the same memory location.
#both x and y will change if only x or only y is changed

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int16)


P.S.: tensor in GPU can't be converted to numpy 

GPU|cuda

In [20]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x= torch.ones(3, device=device)
    y= torch.ones(3)
    y= y.to(device)
    z= x+y
    z= z.to("cpu")
    z= z.numpy()
    print(z)

requires_grad = True: to optimize the tensor variable (tells pytorch that it needs to calculate gradient for the tensor later in optimization steps)

In [21]:
x =  torch.ones(3, requires_grad=True)
print(x)

tensor([1., 1., 1.], requires_grad=True)
